/**
 * Updating from a GitHub release.
 *
 * The releases for this project are archives uploaded by hand, which is a
 * perfectly good distribution channel — GitHub computes a SHA-256 for every
 * asset server-side and reports it on the API, so the download can be verified
 * against something the uploader did not control.
 *
 * The order of operations is the safety:
 *
 *   1. Ask GitHub what is published, and refuse anything without a digest.
 *   2. Refuse to go backwards (see `decideUpdate`).
 *   3. Refuse outright if a knowledge bundle sits inside the install
 *      directory, because there an update *is* a deletion.
 *   4. Download to a staging directory and hash it. A mismatch stops here,
 *      before anything on disk has been touched.
 *   5. Move the current files aside into a timestamped backup — never delete —
 *      then put the new ones in.
 *   6. On any failure after step 5, put the backup back.
 *
 * What is never touched, by construction: the bundle (it lives outside the
 * install directory, and step 3 proves it), and `%APPDATA%` (the updater does
 * not know the path and has no reason to).
 */

import { createHash } from "crypto";
import { cp, mkdir, readdir, readFile, rename, rm, stat, writeFile } from "fs/promises";
import { join, resolve } from "path";
import {
  checkSafeToUpdate,
  decideUpdate,
  sha256FromDigest,
  type InstalledInfo,
  type ReleaseInfo,
  type UpdateVerdict,
} from "../shared/update";

/** Written into the release archive so the version travels with the bytes. */
export const MANIFEST_NAME = "okf-release.json";

export interface ReleaseManifest {
  version: string;
  builtAt: string;
  /** Files the archive is expected to contain at its root, for a sanity check. */
  contains?: string[];
}

/**
 * Directories an update replaces wholesale.
 *
 * An allowlist, not "everything in the archive": the install directory also
 * holds things the archive has no business overwriting — `node_modules`
 * (regenerated by `bun install`), `build/` (regenerated by `bun run
 * build:view` and `build:headless`),
 * and anything the user happens to have put there.
 */
export const REPLACED_PATHS = [
  "src",
  "test",
  "docs",
  "templates",
  "scripts",
  "assets",
  "package.json",
  "bun.lock",
  "tsconfig.json",
  "tsconfig.view.json",
  "vite.config.ts",
  "README.md",
  "CHANGELOG.md",
  "LICENSE",
  "SETUP.bat",
  "SETUP.command",
  "PierrotKnowledge2.bat",
  "PierrotKnowledge2",
] as const;

/**
 * Compiled artefacts that an update has just made stale.
 *
 * `build/` is deliberately not replaced — it is regenerated locally, and the
 * archive does not carry 94 MB binaries. The consequence is easy to miss and
 * defeats the whole update: `PierrotKnowledge2.bat` prefers
 * `build/cli/okf.exe` when it exists, and agent hosts spawn
 * `build/headless/okf-mcp.exe` by the path written into their config. Both
 * keep running the previous release's code until they are rebuilt, so an
 * update can appear to have done nothing at all.
 *
 * Reported rather than deleted: removing the headless binary would leave every
 * agent config pointing at a file that is not there, which is worse than one
 * release behind.
 */
export async function staleCompiledArtifacts(
  installDir: string
): Promise<Array<{ path: string; rebuild: string }>> {
  const candidates = [
    { rel: join("build", "cli", process.platform === "win32" ? "okf.exe" : "okf"), rebuild: "bun run build:cli" },
    {
      rel: join("build", "headless", process.platform === "win32" ? "okf-mcp.exe" : "okf-mcp"),
      rebuild: "bun run build:headless",
    },
  ];

  const found: Array<{ path: string; rebuild: string }> = [];
  for (const candidate of candidates) {
    const path = join(installDir, candidate.rel);
    try {
      await stat(path);
      found.push({ path, rebuild: candidate.rebuild });
    } catch {
      // Never built here, so nothing is stale.
    }
  }
  return found;
}

export interface GithubSource {
  owner: string;
  repo: string;
}

export const DEFAULT_SOURCE: GithubSource = {
  owner: "yuimaruofbook",
  repo: "PierrotKnowledge2",
};

export interface ReleaseAsset {
  name?: string;
  size?: number;
  browser_download_url?: string;
  digest?: string | null;
}

/**
 * Choose which attachment to install.
 *
 * A release can carry more than one — this project's current one carries both
 * the old 285 MB full archive and the 0.57 MB source archive — so "the first
 * zip" is not good enough. A name ending in a version is the one built by
 * `bun run release`, and only that one contains the manifest the update
 * decision needs. Highest version wins, so re-attaching a newer build to an
 * old release still does the right thing.
 */
export function pickAsset(assets: readonly ReleaseAsset[]): ReleaseAsset | undefined {
  const zips = assets.filter((a) => /\.zip$/i.test(a.name ?? ""));

  const versioned = zips
    .map((a) => ({ asset: a, match: /-(\d+)\.(\d+)\.(\d+)\.zip$/i.exec(a.name ?? "") }))
    .filter((x): x is { asset: ReleaseAsset; match: RegExpExecArray } => x.match !== null)
    .sort((a, b) => {
      for (let i = 1; i <= 3; i++) {
        const diff = Number(b.match[i]) - Number(a.match[i]);
        if (diff !== 0) return diff;
      }
      return 0;
    });

  return versioned[0]?.asset ?? zips[0];
}

/** Look up the newest published release. */
export async function fetchLatestRelease(
  source: GithubSource = DEFAULT_SOURCE
): Promise<ReleaseInfo | null> {
  const response = await fetch(
    `https://api.github.com/repos/${source.owner}/${source.repo}/releases/latest`,
    {
      headers: {
        accept: "application/vnd.github+json",
        "x-github-api-version": "2022-11-28",
      },
    }
  );

  if (!response.ok) return null;

  const body = (await response.json()) as {
    tag_name?: string;
    name?: string;
    body?: string;
    html_url?: string;
    published_at?: string;
    assets?: Array<{
      name?: string;
      size?: number;
      browser_download_url?: string;
      digest?: string | null;
    }>;
  };

  const asset = pickAsset(body.assets ?? []);
  if (!asset?.browser_download_url) return null;

  return {
    tag: body.tag_name ?? "",
    name: body.name ?? body.tag_name ?? "",
    notes: body.body ?? "",
    htmlUrl: body.html_url ?? "",
    publishedAt: body.published_at ?? "",
    // Filled in after the archive is downloaded; the API cannot know it.
    version: null,
    assetName: asset.name ?? "",
    assetUrl: asset.browser_download_url,
    assetSize: asset.size ?? 0,
    digest: asset.digest ?? null,
  };
}

/** Download to a file, hashing as it goes so nothing is read twice. */
export async function downloadAndHash(
  url: string,
  to: string,
  onProgress?: (received: number, total: number) => void
): Promise<{ sha256: string; bytes: number }> {
  const response = await fetch(url);
  if (!response.ok || !response.body) {
    throw new Error(`ダウンロードに失敗しました: HTTP ${response.status}`);
  }

  const total = Number(response.headers.get("content-length") ?? 0);
  const hash = createHash("sha256");
  let received = 0;

  // Written as it arrives rather than buffered: these archives are hundreds
  // of megabytes, and holding one in memory to hash it would cost more than
  // the whole application does.
  const writer = Bun.file(to).writer();
  try {
    for await (const chunk of response.body as unknown as AsyncIterable<Uint8Array>) {
      hash.update(chunk);
      writer.write(chunk);
      received += chunk.byteLength;
      onProgress?.(received, total);
    }
  } finally {
    await writer.end();
  }

  return { sha256: hash.digest("hex"), bytes: received };
}

export interface UpdatePlan {
  verdict: UpdateVerdict;
  release: ReleaseInfo;
  installed: InstalledInfo;
}

/**
 * Where the application is installed.
 *
 * Not derivable from `import.meta.dir` alone: compiled with
 * `bun build --compile` that is a path *inside* the executable (`B:/~BUN/…`),
 * so resolving upwards from it lands on `B:\` and every read fails. The same
 * trap as the rmux entry point, and found the same way — by running the built
 * binary rather than the source.
 *
 * So each plausible root is tried and then *verified* by looking for the files
 * that only this project's root has. A wrong guess here would have the updater
 * replace the wrong directory.
 */
export async function findInstallDir(options?: {
  moduleDir?: string;
  execPath?: string;
  cwd?: string;
}): Promise<string | null> {
  const moduleDir = options?.moduleDir ?? import.meta.dir;
  const execPath = options?.execPath ?? process.execPath;
  const cwd = options?.cwd ?? process.cwd();

  const execDir = execPath.split(/[\\/]/).slice(0, -1).join("/");

  const candidates = [
    // Running from source: src/bun/ → root.
    resolve(moduleDir, "../.."),
    // Compiled to build/cli/okf.exe → root.
    resolve(execDir, "../.."),
    // Started from the project directory.
    cwd,
    resolve(cwd, ".."),
  ];

  for (const candidate of candidates) {
    if (await looksLikeInstall(candidate)) return candidate;
  }
  return null;
}

/** A root has our package.json and the source tree beside it. */
async function looksLikeInstall(dir: string): Promise<boolean> {
  try {
    const pkg = JSON.parse(await readFile(join(dir, "package.json"), "utf8")) as {
      name?: string;
    };
    if (!pkg.name) return false;
    return await readdir(join(dir, "src"))
      .then(() => true)
      .catch(() => false);
  } catch {
    return false;
  }
}

/** Read the installed version from `package.json` plus the update record. */
export async function readInstalled(installDir: string): Promise<InstalledInfo> {
  const pkg = JSON.parse(await readFile(join(installDir, "package.json"), "utf8")) as {
    version?: string;
  };

  let record: Partial<InstalledInfo> = {};
  try {
    record = JSON.parse(await readFile(join(installDir, MANIFEST_NAME), "utf8")) as InstalledInfo;
  } catch {
    // No record: this install predates the updater, which is fine.
  }

  return {
    version: record.version ?? pkg.version ?? "0.0.0",
    ...(record.tag ? { tag: record.tag } : {}),
    ...(record.publishedAt ? { publishedAt: record.publishedAt } : {}),
  };
}

/**
 * Everything that can be decided before downloading 285 MB.
 *
 * `releaseVersion` comes from the caller because only the archive knows it,
 * and reading the archive means fetching it. Callers that have not fetched yet
 * pass null and get told to look.
 */
export async function planUpdate(options: {
  installDir: string;
  knownBundles: readonly string[];
  source?: GithubSource;
  releaseVersion?: string | null;
}): Promise<UpdatePlan | { verdict: UpdateVerdict; release: null; installed: InstalledInfo }> {
  const installed = await readInstalled(options.installDir);

  const safety = checkSafeToUpdate({
    installDir: options.installDir,
    knownBundles: options.knownBundles,
  });
  if (!safety.ok) {
    return {
      verdict: { action: "refuse", reason: safety.problems.join("\n") },
      release: null,
      installed,
    };
  }

  const release = await fetchLatestRelease(options.source);
  if (!release) {
    return {
      verdict: { action: "refuse", reason: "リリース情報を取得できませんでした。" },
      release: null,
      installed,
    };
  }

  release.version = options.releaseVersion ?? null;
  return { verdict: decideUpdate(installed, release), release, installed };
}

export interface ApplyResult {
  backupDir: string;
  replaced: string[];
}

/**
 * Swap an extracted tree into place, keeping the old one.
 *
 * Nothing is deleted. The previous copy of each replaced path is moved into a
 * timestamped backup directory, so a bad release is undone by moving them
 * back — which `rollback` does.
 */
export async function applyUpdate(options: {
  installDir: string;
  /** Root of the extracted archive — the directory holding `src/`, `package.json`… */
  stagedRoot: string;
  backupRoot?: string;
}): Promise<ApplyResult> {
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backupDir = options.backupRoot ?? join(options.installDir, ".okf-backup", stamp);
  await mkdir(backupDir, { recursive: true });

  const replaced: string[] = [];
  const done: Array<{ name: string; from: string }> = [];

  try {
    for (const name of REPLACED_PATHS) {
      const incoming = join(options.stagedRoot, name);
      if (!(await exists(incoming))) continue;

      const current = join(options.installDir, name);
      if (await exists(current)) {
        await rename(current, join(backupDir, name));
        done.push({ name, from: current });
      }

      await cp(incoming, current, { recursive: true });
      replaced.push(name);
    }
  } catch (error) {
    // Put back whatever was moved before the failure, so a half-applied
    // update never survives.
    for (const { name, from } of done.reverse()) {
      await rm(from, { recursive: true, force: true }).catch(() => {});
      await rename(join(backupDir, name), from).catch(() => {});
    }
    throw error;
  }

  return { backupDir, replaced };
}

/** Undo an `applyUpdate` from its backup directory. */
export async function rollback(installDir: string, backupDir: string): Promise<string[]> {
  const restored: string[] = [];

  for (const name of await readdir(backupDir)) {
    const target = join(installDir, name);
    await rm(target, { recursive: true, force: true }).catch(() => {});
    await rename(join(backupDir, name), target);
    restored.push(name);
  }

  return restored;
}

/** Record what was installed, so the next check has something to compare. */
export async function writeInstallRecord(
  installDir: string,
  info: InstalledInfo
): Promise<void> {
  await writeFile(
    join(installDir, MANIFEST_NAME),
    `${JSON.stringify(info, null, 2)}\n`,
    "utf8"
  );
}

/** Verify a download against the digest GitHub reported. */
export function digestMatches(expected: string | null, actual: string): boolean {
  const want = sha256FromDigest(expected);
  return want !== null && want === actual.toLowerCase();
}

async function exists(path: string): Promise<boolean> {
  return await Bun.file(resolve(path))
    .exists()
    .catch(() => false)
    .then(async (isFile) => {
      if (isFile) return true;
      // Bun.file().exists() is false for directories, so ask readdir.
      return await readdir(path)
        .then(() => true)
        .catch(() => false);
    });
}
